import { useEffect, useRef, useState } from 'react';
import { applyGrowth, calculateScenario, defaultScenario, RESOURCE_KEYS, RESOURCE_META, validateScenario } from './calculations.js';

const STORAGE_KEY = 'ppr-calculator-v1';
const integer = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 });
const decimal = new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 });
const precise = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });
const percent = value => Number.isFinite(value) ? `${decimal.format(value * 100)}%` : '—';
const fmt = value => Number.isFinite(value) ? integer.format(value) : '—';
const fmt1 = value => Number.isFinite(value) ? decimal.format(value) : '—';
const PROVENANCE_GROUPS = [['demand', 'Traffic demand'], ['routing', 'Check-in routes'], ['bags', 'Bag participation & bag drop'], ['security', 'Security & transfers'], ['counter', 'Counter service & units'], ['kiosk', 'Kiosk service & units'], ['bagDrop', 'Bag-drop service & units'], ['lanes', 'Security lanes & units'], ['queues', 'Utilisation & queue targets']];
function provenanceSummary(scenario) {
  const statuses = PROVENANCE_GROUPS.map(([key]) => scenario.provenance?.[key] || 'illustrative');
  if (statuses.every(s => s === 'measured')) return 'All groups marked measured';
  if (statuses.some(s => s !== 'illustrative')) return 'Mixed assumption sources';
  return 'Illustrative assumptions';
}

function initialState() {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY));
    if (saved?.schemaVersion === 1 && validateScenario(saved.baseline).length === 0 && (!saved.whatif || validateScenario(saved.whatif).length === 0)) {
      return { baseline: saved.baseline, whatif: saved.whatif || null, active: saved.whatif && saved.active === 'whatif' ? 'whatif' : 'baseline', mode: saved.mode === 'capacity' ? 'capacity' : 'demand' };
    }
  } catch { /* Keep the documented starting scenario. */ }
  return { baseline: defaultScenario(), whatif: null, active: 'baseline', mode: 'demand' };
}

function Icon({ name, size = 19 }) {
  const path = {
    chevron: <path d="m6 9 6 6 6-6" />,
    arrow: <><path d="M4 12h16" /><path d="m14 6 6 6-6 6" /></>,
    info: <><circle cx="12" cy="12" r="9" /><path d="M12 11v6" /><circle cx="12" cy="8" r=".8" fill="currentColor" stroke="none" /></>,
    download: <><path d="M12 3v12" /><path d="m7 11 5 5 5-5" /><path d="M4 18v3h16v-3" /></>,
    sliders: <><path d="M4 7h16M4 17h16" /><circle cx="9" cy="7" r="2" fill="white" /><circle cx="16" cy="17" r="2" fill="white" /></>,
    check: <path d="m4 12 5 5L20 6" />,
    warning: <><path d="M12 3 2 21h20L12 3Z" /><path d="M12 9v5m0 3v.5" /></>,
  }[name];
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{path}</svg>;
}

function NumberField({ label, value, onChange, unit, hint, min = 0, max, step = 'any', slider, disabled = false }) {
  const id = label.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return <div className={`field ${disabled ? 'field-disabled' : ''}`}>
    <div className="field-top"><label htmlFor={id}>{label}</label><div className="field-value"><input id={id} type="number" inputMode="decimal" value={value} min={min} max={max} step={step} disabled={disabled} onChange={e => onChange(e.target.value === '' ? '' : Number(e.target.value))} aria-describedby={hint ? `${id}-hint` : undefined} /><span>{unit}</span></div></div>
    {slider && <input className="range" type="range" min={slider.min ?? min} max={slider.max ?? max} step={slider.step ?? 1} value={Number.isFinite(Number(value)) ? Math.min(slider.max ?? max, Math.max(slider.min ?? min, Number(value))) : 0} disabled={disabled} onChange={e => onChange(Number(e.target.value))} aria-label={`${label} slider`} style={{ '--progress': `${((Number(value) - (slider.min ?? min)) / ((slider.max ?? max) - (slider.min ?? min))) * 100}%` }} />}
    {hint && <small id={`${id}-hint`}>{hint}</small>}
  </div>;
}

function Toggle({ checked, onChange, label, hint, disabled }) {
  return <label className="toggle-row"><span><strong>{label}</strong>{hint && <small>{hint}</small>}</span><input type="checkbox" checked={Boolean(checked)} disabled={disabled} onChange={e => onChange(e.target.checked)} /><span className="switch" aria-hidden="true" /></label>;
}

function download(name, mime, data) {
  const url = URL.createObjectURL(new Blob([data], { type: mime }));
  const a = document.createElement('a');
  a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function csvCell(value) { return `"${String(value ?? '').replaceAll('"', '""')}"`; }

function Methodology() {
  return <details className="methodology" id="methodology"><summary><span>Methodology, assumptions & sources</span><Icon name="chevron" /></summary>
    <div className="method-grid">
      <section><h3>Demand and routes</h3><p>The direct mode starts with originating passengers reaching the modelled area in the selected hour. Annual airport and annual departing traffic are alternative inputs. The annual bridge applies the stated departure, originating, design-day and design-hour factors once each.</p><p>Staffed check-in includes bag acceptance in its service time. Kiosk users with bags visit both kiosk and bag drop. Online users visit only the facilities selected by their bag and tag needs. Security includes originating passengers plus the entered transfer rescreening flow.</p></section>
      <section><h3>Resource and queue maths</h3><p>Workload = transactions × seconds per transaction. Throughput units = ceiling(workload ÷ 3,600 ÷ target utilisation). The queue model is M/M/c: one shared queue, identical open servers, steady independent arrivals and exponential service times. The final open-unit recommendation is the larger of the throughput and queue-target needs for each pool.</p><p>A lane's entered passengers/hour is effective whole-lane throughput. Its queue result is a lane-equivalent approximation. Short-burst queue results are steady-rate stress estimates; they do not simulate the carry-over of a queue between intervals.</p></section>
      <section><h3>Capacity and limits</h3><p>Capacity mode uses currently open units, routing shares, utilisation targets and queue targets. It converts each process limit back to originating passengers/hour and identifies the lowest one. Separate dedicated pools are sized separately. Installed or reserved units do not add capacity until open.</p><p>This is an indicative process-planning model. Actual airport service rates, queue configuration, passenger arrival profiles, transfer flows and staffing should replace illustrative assumptions before investment decisions.</p></section>
      <section><h3>References</h3><ul><li><a href="https://www.iata.org/contentassets/d1d4d535bf1c4ba695f43e9beff8294f/demand-triggers-for-airport-investments.pdf" target="_blank" rel="noreferrer">IATA — Demand Triggers for Airport Investments</a></li><li><a href="https://crp.trb.org/acrpwebresource2/acrp-report-25-airport-passenger-terminal-planning-and-design-volume-2-spreadsheet-models-and-users-guide/" target="_blank" rel="noreferrer">ACRP Report 25 — Terminal planning models</a></li><li><a href="https://web.mit.edu/urban_or_book/www/book/chapter4/4.6.2.html" target="_blank" rel="noreferrer">MIT — Multi-server queue model</a></li><li><a href="https://www.iata.org/en/programs/passenger/common-use/" target="_blank" rel="noreferrer">IATA — Common-use processing</a></li></ul></section>
    </div>
  </details>;
}

export default function App() {
  const [state, setState] = useState(initialState);
  const [notice, setNotice] = useState('');
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const fileInput = useRef(null);
  const { baseline, whatif, active, mode } = state;
  const scenario = active === 'whatif' && whatif ? whatif : baseline;
  const locked = active === 'baseline' && Boolean(whatif);
  const result = calculateScenario(scenario, mode);
  const baselineResult = whatif ? calculateScenario(baseline, mode) : null;
  const whatifResult = whatif ? calculateScenario(whatif, mode) : null;

  useEffect(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify({ schemaVersion: 1, ...state })); } catch { /* Browser storage may be unavailable. */ } }, [state]);

  function changeScenario(mutate) {
    if (locked) return;
    setState(previous => {
      const key = previous.active === 'whatif' && previous.whatif ? 'whatif' : 'baseline';
      const next = structuredClone(previous[key]);
      mutate(next);
      return { ...previous, [key]: next };
    });
  }
  const setField = (key, val) => changeScenario(next => { next[key] = val; });
  const setProvenance = (key, val) => changeScenario(next => { next.provenance ??= {}; next.provenance[key] = val; });
  const setResource = (key, field, val) => changeScenario(next => {
    next.resources[key][field] = val;
    if (field === 'open' && Number.isFinite(val) && val > next.resources[key].installed - next.resources[key].unavailable) next.resources[key].installed = val + next.resources[key].unavailable;
  });
  function createWhatif() { setState(previous => ({ ...previous, whatif: structuredClone(previous.baseline), active: 'whatif' })); setNotice('What-if is ready. Edit its assumptions to compare.'); }
  function presetGrowth(p) {
    setState(previous => {
      const source = previous.whatif ?? previous.baseline;
      return { ...previous, whatif: applyGrowth(source, p), active: 'whatif' };
    });
    setNotice(`Added ${p}% traffic to the what-if scenario.`);
  }
  function presetOnline() {
    setState(previous => {
      const next = structuredClone(previous.whatif ?? previous.baseline);
      const move = Math.min(20, next.counterShare);
      next.counterShare -= move; next.onlineShare += move;
      return { ...previous, whatif: next, active: 'whatif' };
    });
    setNotice('Moved up to 20 percentage points from counters to online check-in.');
  }
  function exportJSON() {
    download('passenger-processing-scenarios.json', 'application/json', JSON.stringify({ schemaVersion: 1, exportedAt: new Date().toISOString(), baseline, whatif, active, mode }, null, 2)); setShowExport(false);
  }
  function exportCSV() {
    const rows = [['Scenario', 'Input basis', 'Originating passengers/hour', 'Process', 'Visits/hour', 'Transactions/hour', 'Open units', 'Throughput units', 'Queue-target units', 'Recommended open units', 'Mean queue min', 'Target met', 'Originating capacity/hour']];
    for (const [label, data, calc] of [['Baseline', baseline, calculateScenario(baseline, mode)], ['What-if', whatif, whatif && calculateScenario(whatif, mode)]]) {
      if (!data || !calc?.valid) continue;
      for (const key of RESOURCE_KEYS) { const r = calc.resources[key]; rows.push([label, data.demandBasis, calc.originating, RESOURCE_META[key].label, r.visits, r.transactions, data.resources[key].open, r.throughput, r.queueUnits, r.recommended, r.weightedWait, r.targetMet, r.capacity]); }
    }
    download('passenger-processing-results.csv', 'text/csv;charset=utf-8', '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\r\n')); setShowExport(false);
  }
  async function importJSON(file) {
    try {
      const data = JSON.parse(await file.text());
      if (data.schemaVersion !== 1 || !data.baseline || validateScenario(data.baseline).length || (data.whatif && validateScenario(data.whatif).length)) throw new Error('The scenario file has invalid or unsupported inputs.');
      setState({ baseline: data.baseline, whatif: data.whatif ?? null, active: data.whatif && data.active === 'whatif' ? 'whatif' : 'baseline', mode: data.mode === 'capacity' ? 'capacity' : 'demand' });
      setNotice('Scenarios imported.');
    } catch (error) { setNotice(error.message || 'Could not read this scenario file.'); }
    if (fileInput.current) fileInput.current.value = '';
    setShowExport(false);
  }

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#top" aria-label="Passenger Processing & Resource Calculator home"><span className="brand-mark" aria-hidden="true"><i></i><i></i></span><strong>Passenger Processing & Resource Calculator</strong><span>Plan. Size. Operate.</span></a><nav><a href="#methodology">Methodology</a><div className="export-wrap"><button type="button" className="header-action" onClick={() => setShowExport(!showExport)} aria-expanded={showExport}><Icon name="download" size={16} /> Export</button>{showExport && <div className="export-menu"><button onClick={exportJSON}>Download scenarios · JSON</button><button onClick={exportCSV}>Download results · CSV</button><button onClick={() => { window.print(); setShowExport(false); }}>Print report</button><button onClick={() => fileInput.current?.click()}>Import scenario · JSON</button></div>}</div><button type="button" className="header-action" onClick={() => { if (window.confirm('Reset the calculator to illustrative assumptions?')) { setState({ baseline: defaultScenario(), whatif: null, active: 'baseline', mode: 'demand' }); setNotice('Illustrative assumptions restored.'); } }}>Reset</button></nav></header>
    <input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={e => e.target.files?.[0] && importJSON(e.target.files[0])} />
    <main id="top"><div className="intro"><div><h1>From passengers to processing capacity.</h1><p>Size check-in, bag drop and security for a defined busy period.</p></div><div className="route-motif" aria-hidden="true">ARRIVE <span>→</span> PROCESS <span>→</span> DEPART</div></div>
      <div className="mode-bar" role="tablist" aria-label="Calculation direction"><button role="tab" aria-selected={mode === 'demand'} className={mode === 'demand' ? 'active' : ''} onClick={() => setState({ ...state, mode: 'demand' })}>Demand <Icon name="arrow" size={16} /> resources</button><button role="tab" aria-selected={mode === 'capacity'} className={mode === 'capacity' ? 'active' : ''} onClick={() => setState({ ...state, mode: 'capacity' })}>Resources <Icon name="arrow" size={16} /> capacity</button><span>{mode === 'demand' ? 'Estimate open units needed' : 'Find the limiting process'}</span></div>
      {notice && <div className="notice" role="status">{notice}<button aria-label="Dismiss message" onClick={() => setNotice('')}>×</button></div>}
      <div className="workspace">
        <section className="panel inputs-panel" aria-label="Calculator inputs">
          <div className="panel-heading"><div><h2>Traffic & assumptions</h2><p>{mode === 'demand' ? 'Change the demand or how passengers are processed.' : 'Enter the units you can open and the expected demand.'}</p></div><span className="assumption-badge">Illustrative · editable</span></div>
          <div className="scenario-bar"><div className="scenario-tabs"><button className={active === 'baseline' ? 'active' : ''} onClick={() => setState({ ...state, active: 'baseline' })}>Baseline</button>{whatif && <button className={active === 'whatif' ? 'active' : ''} onClick={() => setState({ ...state, active: 'whatif' })}>What-if</button>}</div>{whatif ? <button className="plain-button" onClick={() => { setState({ ...state, whatif: null, active: 'baseline' }); setNotice('Comparison cleared; baseline is editable again.'); }}>Clear comparison</button> : <button className="plain-button" onClick={createWhatif}>+ Create what-if</button>}</div>
          {locked && <p className="locked-note">Baseline is frozen for comparison. Open What-if to make changes.</p>}
          <div className="input-section"><div className="section-label"><h3>Demand basis</h3><span>One basis at a time</span></div><div className="basis-select"><select value={scenario.demandBasis} disabled={locked} onChange={e => setField('demandBasis', e.target.value)} aria-label="Passenger demand basis"><option value="direct">Originating arrivals · peak hour</option><option value="departing-hour">Departing PAX · peak hour</option><option value="annual-airport">Annual airport PAX</option><option value="annual-departing">Annual departing PAX</option></select></div>
            {scenario.demandBasis === 'direct' && <NumberField label="Originating passengers" value={scenario.directOriginating} onChange={v => setField('directOriginating', v)} unit="PAX / h" slider={{ min: 0, max: 10000, step: 50 }} disabled={locked} hint="Passengers reaching this processing area in the selected hour." />}
            {scenario.demandBasis === 'departing-hour' && <NumberField label="Departing passengers" value={scenario.departingHour} onChange={v => setField('departingHour', v)} unit="PAX / h" slider={{ min: 0, max: 12000, step: 50 }} disabled={locked} hint="Applies the originating share below; transfers bypass check-in by default." />}
            {scenario.demandBasis === 'annual-airport' && <NumberField label="Annual airport passengers" value={scenario.annualAirport} onChange={v => setField('annualAirport', v)} unit="PAX / yr" slider={{ min: 0, max: 100000000, step: 100000 }} disabled={locked} />}
            {scenario.demandBasis === 'annual-departing' && <NumberField label="Annual departing passengers" value={scenario.annualDeparting} onChange={v => setField('annualDeparting', v)} unit="PAX / yr" slider={{ min: 0, max: 50000000, step: 100000 }} disabled={locked} />}
            {scenario.demandBasis !== 'direct' && <p className="basis-note">{scenario.demandBasis.startsWith('annual') ? 'Annual traffic is converted through editable design-day and design-hour assumptions below.' : 'The originating share is editable below.'}</p>}
          </div>
          <div className="input-section route-inputs"><div className="section-label"><h3>Passenger routes</h3><span>Shares of originating PAX</span></div><div className="tri-fields"><NumberField label="Staffed check-in" value={scenario.counterShare} onChange={v => setField('counterShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Kiosk check-in" value={scenario.kioskShare} onChange={v => setField('kioskShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Online check-in" value={scenario.onlineShare} onChange={v => setField('onlineShare', v)} unit="%" max={100} disabled={locked} /></div><div className={`total-share ${Math.abs(Number(scenario.counterShare) + Number(scenario.kioskShare) + Number(scenario.onlineShare) - 100) > 1e-7 ? 'bad' : ''}`}>Route share total <strong>{fmt1(Number(scenario.counterShare) + Number(scenario.kioskShare) + Number(scenario.onlineShare))}%</strong><span>must be 100%</span></div><div className="two-fields"><NumberField label="Kiosk users checking bags" value={scenario.kioskBagShare} onChange={v => setField('kioskBagShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Online users checking bags" value={scenario.onlineBagShare} onChange={v => setField('onlineBagShare', v)} unit="%" max={100} disabled={locked} /></div></div>
          <div className="input-section resource-inputs"><div className="section-label"><h3>Process settings</h3><span>Per transaction or whole lane</span></div><div className="resource-input-grid">{RESOURCE_KEYS.map(key => { const r = scenario.resources[key]; return <div className="resource-input-card" key={key}><div className="resource-input-title"><span className={`resource-icon ${key}`}>{key === 'counter' ? 'C' : key === 'kiosk' ? 'K' : key === 'bagDrop' ? 'B' : 'S'}</span><strong>{RESOURCE_META[key].short}</strong></div><div className="compact-field"><label htmlFor={`service-${key}`}>{key === 'security' ? 'Lane throughput' : 'Service time'}</label><div><input id={`service-${key}`} type="number" min="0.000001" step="any" disabled={locked || (key === 'bagDrop' && scenario.bagServiceMode === 'decomposed')} value={key === 'security' ? Number.isFinite(3600 / Number(r.serviceSec)) ? Math.round(3600 / Number(r.serviceSec) * 100) / 100 : '' : r.serviceSec} onChange={e => setResource(key, 'serviceSec', e.target.value === '' ? '' : key === 'security' ? 3600 / Number(e.target.value) : Number(e.target.value))} /><span>{key === 'security' ? 'PAX/h' : 'sec'}</span></div></div><div className="compact-field"><label htmlFor={`util-${key}`}>Utilisation target</label><div><input id={`util-${key}`} type="number" min="0.001" max="100" step="any" value={r.utilisation} disabled={locked} onChange={e => setResource(key, 'utilisation', e.target.value === '' ? '' : Number(e.target.value))} /><span>%</span></div></div>{mode === 'capacity' && <div className="compact-field"><label htmlFor={`open-${key}`}>Open units</label><div><input id={`open-${key}`} type="number" min="0" step="1" value={r.open} disabled={locked} onChange={e => setResource(key, 'open', e.target.value === '' ? '' : Number(e.target.value))} /><span>units</span></div></div>}</div>; })}</div></div>
          <div className="quick-actions"><span>What changes if…</span><button onClick={() => presetGrowth(10)}>+10% traffic</button><button onClick={() => presetGrowth(30)}>+30% traffic</button><button onClick={presetOnline}>+20 pp online</button></div>
        </section>
        <section className="panel results-panel" aria-label="Calculator results"><div className="panel-heading"><div><h2>{mode === 'demand' ? 'Resources required' : 'Available capacity'}</h2><p>{result.valid ? `${fmt1(result.originating)} originating PAX / hour · ${scenario.burstEnabled ? '15-minute stress rate' : 'hourly rate'}` : 'Complete the highlighted inputs to calculate.'}</p></div><span className="live-pill"><i /> Live calculation</span></div>
          {!result.valid ? <div className="error-box" role="alert"><strong>Check these inputs</strong><ul>{result.errors.slice(0, 7).map((error, i) => <li key={i}>{error}</li>)}</ul>{result.errors.length > 7 && <p>There are {result.errors.length - 7} additional input errors.</p>}</div> : <>
            <div className="hero-metric"><span>{mode === 'demand' ? 'Planning demand' : 'Modelled system capacity'}</span><div><strong>{mode === 'demand' ? fmt1(result.originating) : Number.isFinite(result.systemCapacity) ? fmt1(result.systemCapacity) : '—'}</strong><em>originating PAX / hour</em></div><small>{mode === 'demand' ? 'Each process uses its own share of these passengers.' : result.bottlenecks.length ? `Limited by ${result.bottlenecks.map(k => RESOURCE_META[k].short.toLowerCase()).join(', ')}.` : 'No selected process limits originating demand.'}</small></div>
            {mode === 'capacity' && result.backgroundExceeded && <div className="capacity-alert" role="status"><Icon name="warning" size={18} /><span>Transfer screening demand already exceeds the selected open-lane capacity.</span></div>}
            <div className="resource-results">{RESOURCE_KEYS.map(key => { const r = result.resources[key]; const target = scenario.resources[key]; return <article className={`resource-result ${key}`} key={key}><div className="result-top"><span>{RESOURCE_META[key].label}</span><span className="result-unit">{mode === 'demand' ? 'open units needed' : 'currently open'}</span></div><div className="result-number"><strong>{mode === 'demand' ? fmt(r.recommended) : fmt(target.open)}</strong><span>{RESOURCE_META[key].unit}</span></div><div className="result-secondary"><span>{fmt1(r.visits)} visits/h</span><span>{r.status === 'ok' ? `${precise.format(r.weightedWait)} min mean queue` : r.status === 'unavailable' ? 'No service available' : 'No steady queue estimate'}</span></div><div className="resource-bar"><i style={{ width: `${Math.min(100, Math.max(0, r.maxUtilisation * 100))}%` }} /></div><div className="result-foot"><span>Utilisation {percent(r.maxUtilisation)}</span><span className={r.targetMet ? 'pass' : 'fail'}>{r.targetMet ? 'Target met' : 'Review target'}</span></div></article>; })}</div>
            <div className="flow-strip"><div><strong>{fmt1(result.originating)}</strong><span>originating PAX</span></div><Icon name="arrow" size={17} /><div><strong>{fmt1(result.resources.counter.visits + result.resources.kiosk.visits)}</strong><span>check-in visits</span></div><Icon name="arrow" size={17} /><div><strong>{fmt1(result.resources.bagDrop.visits)}</strong><span>bag-drop visits</span></div><Icon name="arrow" size={17} /><div><strong>{fmt1(result.resources.security.visits)}</strong><span>originating security visits</span></div></div>
            <p className="flow-note">Visits can exceed unique passengers: some kiosk users also use bag drop. Staffed check-in includes bag acceptance.</p>
            <div className="detail-header"><h3>{mode === 'demand' ? 'Why these unit counts?' : 'Which process limits capacity?'}</h3><span>{mode === 'demand' ? 'Throughput + queue target' : 'Current route mix'}</span></div><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Process</th><th>Transactions/h</th><th>{mode === 'demand' ? 'Throughput' : 'Usable PAX/h'}</th><th>{mode === 'demand' ? 'Queue target' : 'Demand ÷ capacity'}</th><th>{mode === 'demand' ? 'Open needed' : 'Shortfall'}</th></tr></thead><tbody>{RESOURCE_KEYS.map(key => { const r = result.resources[key]; const shortfall = Math.max(0, r.recommended - Number(scenario.resources[key].open)); return <tr key={key}><th scope="row">{RESOURCE_META[key].short}</th><td>{fmt1(r.transactions)}</td><td>{mode === 'demand' ? fmt(r.throughput) : Number.isFinite(r.capacity) ? fmt1(r.capacity) : '—'}</td><td>{mode === 'demand' ? fmt(r.queueUnits) : Number.isFinite(r.capacity) && r.capacity > 0 ? percent(result.originating / r.capacity) : '—'}</td><td className={mode === 'capacity' && shortfall ? 'warn-cell' : ''}>{mode === 'demand' ? fmt(r.recommended) : shortfall ? `+${shortfall}` : '0'}</td></tr>; })}</tbody></table></div>
            <details className="queue-details"><summary>Queue results by process <Icon name="chevron" size={17} /></summary><div className="queue-detail-grid">{RESOURCE_KEYS.map(key => { const resource = result.resources[key]; const target = scenario.resources[key]; return <div className="queue-detail-card" key={key}><strong>{RESOURCE_META[key].label}</strong><span>Target: {fmt1(target.targetPercent)}% within {fmt1(target.targetMinutes)} min · install {fmt(resource.installedRecommended)} incl. reserve</span>{resource.pools.map((pool, i) => <div className="pool-detail" key={i}><b>{pool.name} · {fmt(pool.chosen)} open</b><dl><div><dt>Transactions/h</dt><dd>{fmt1(pool.lambda)}</dd></div><div><dt>Utilisation</dt><dd>{percent(pool.q.rho)}</dd></div><div><dt>Within target</dt><dd>{pool.q.status === 'ok' ? percent(pool.q.serviceLevel) : '—'}</dd></div><div><dt>Mean wait</dt><dd>{pool.q.status === 'ok' ? `${precise.format(pool.q.meanWaitMinutes)} min` : '—'}</dd></div><div><dt>95th-percentile wait</dt><dd>{pool.q.status === 'ok' ? `${precise.format(pool.q.p95Minutes)} min` : '—'}</dd></div><div><dt>Mean queue</dt><dd>{pool.q.status === 'ok' ? `${precise.format(pool.q.meanQueue)} transactions` : '—'}</dd></div></dl>{pool.q.status !== 'ok' && <small>No finite steady-state estimate for this pool.</small>}</div>)}</div>; })}</div></details>
            <div className="queue-note"><Icon name="info" size={17} /><p>Queue figures use an indicative steady-flow model. A passenger's total journey time also depends on walking, downstream queues and the actual arrival pattern.</p></div>
          </>}
        </section>
      </div>
      <section className="advanced panel"><button className="advanced-heading" aria-expanded={showAdvanced} onClick={() => setShowAdvanced(!showAdvanced)}><Icon name="sliders" size={20} /><span><strong>Advanced assumptions</strong><small>Queue targets, annual conversion, bursts, bags, transfers and dedicated pools</small></span><Icon name="chevron" size={20} /></button>{showAdvanced && <div className="advanced-body">
        <div className="advanced-group"><h3>Queue & equipment</h3><p>All queue targets apply to transactions starting service. Installed units remain separate from open units.</p><div className="advanced-resource-grid">{RESOURCE_KEYS.map(key => { const r = scenario.resources[key]; return <div className="advanced-resource" key={key}><h4>{RESOURCE_META[key].label}</h4><div className="mini-grid"><NumberField label={`${RESOURCE_META[key].short} target`} value={r.targetPercent} onChange={v => setResource(key, 'targetPercent', v)} unit="%" max={99.999999} disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} within`} value={r.targetMinutes} onChange={v => setResource(key, 'targetMinutes', v)} unit="min" disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} installed`} value={r.installed} onChange={v => setResource(key, 'installed', v)} unit="units" step="1" disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} unavailable`} value={r.unavailable} onChange={v => setResource(key, 'unavailable', v)} unit="units" step="1" disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} reserve`} value={r.reserve} onChange={v => setResource(key, 'reserve', v)} unit="units" step="1" disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} min. open`} value={r.minimum} onChange={v => setResource(key, 'minimum', v)} unit="units" step="1" disabled={locked} /></div></div>; })}</div></div>
        <div className="advanced-group"><h3>Traffic conversion & routing</h3><div className="advanced-grid"><NumberField label="Departure share of airport PAX" value={scenario.departureShare} onChange={v => setField('departureShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Originating share of departures" value={scenario.originatingShare} onChange={v => setField('originatingShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Operating days" value={scenario.operatingDays} onChange={v => setField('operatingDays', v)} unit="days" min={1} max={366} disabled={locked} /><NumberField label="Design day ÷ average day" value={scenario.designDayFactor} onChange={v => setField('designDayFactor', v)} unit="×" min={0.000001} disabled={locked} /><NumberField label="Design-hour share of design day" value={scenario.designHourShare} onChange={v => setField('designHourShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Online bag users needing kiosk tag" value={scenario.onlineTagKioskShare} onChange={v => setField('onlineTagKioskShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Counter users checking bags" value={scenario.counterBagShare} onChange={v => setField('counterBagShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Originating PAX using this security" value={scenario.securityOriginShare} onChange={v => setField('securityOriginShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Transfer PAX arriving at security" value={scenario.transferSecurityPassengers} onChange={v => setField('transferSecurityPassengers', v)} unit="PAX/h" disabled={locked} /><NumberField label="Transfer rescreening share" value={scenario.transferRescreenShare} onChange={v => setField('transferRescreenShare', v)} unit="%" max={100} disabled={locked} /></div></div>
        <div className="advanced-group"><h3>Bag-drop transaction</h3><div className="segmented inline"><button className={scenario.bagDropType === 'self-service' ? 'active' : ''} disabled={locked} onClick={() => setField('bagDropType', 'self-service')}>Self-service</button><button className={scenario.bagDropType === 'staffed' ? 'active' : ''} disabled={locked} onClick={() => setField('bagDropType', 'staffed')}>Staffed</button></div><div className="segmented inline"><button className={scenario.bagServiceMode === 'inclusive' ? 'active' : ''} disabled={locked} onClick={() => setField('bagServiceMode', 'inclusive')}>All-inclusive time</button><button className={scenario.bagServiceMode === 'decomposed' ? 'active' : ''} disabled={locked} onClick={() => setField('bagServiceMode', 'decomposed')}>Build from steps</button></div>{scenario.bagServiceMode === 'decomposed' && <div className="advanced-grid"><NumberField label="Fixed seconds per transaction" value={scenario.bagFixedSeconds} onChange={v => setField('bagFixedSeconds', v)} unit="sec" disabled={locked} /><NumberField label="Seconds per bag" value={scenario.bagSecondsPerBag} onChange={v => setField('bagSecondsPerBag', v)} unit="sec" disabled={locked} /><NumberField label="Bags per bag-drop transaction" value={scenario.bagsPerTransaction} onChange={v => setField('bagsPerTransaction', v)} unit="bags" disabled={locked} /><NumberField label="Exception share" value={scenario.bagExceptionShare} onChange={v => setField('bagExceptionShare', v)} unit="%" max={100} disabled={locked} /><NumberField label="Extra seconds if exception" value={scenario.bagExceptionExtraSeconds} onChange={v => setField('bagExceptionExtraSeconds', v)} unit="sec" disabled={locked} /></div>}<p className="explain">The all-inclusive time and the step-built time are alternatives; only the selected one enters the calculation.</p></div>
        <div className="advanced-group"><h3>Bursts & dedicated pools</h3><Toggle label="Check the busiest 15 minutes" hint="Treats the selected quarter-hour rate as a steady stress case." checked={scenario.burstEnabled} disabled={locked} onChange={v => setField('burstEnabled', v)} /><div className="advanced-resource-grid">{RESOURCE_KEYS.map(key => { const r = scenario.resources[key]; return <div className="advanced-resource" key={key}><h4>{RESOURCE_META[key].label}</h4><div className="mini-grid"><NumberField label={`${RESOURCE_META[key].short} busiest 15 min`} value={r.burstShare} onChange={v => setResource(key, 'burstShare', v)} unit="% of hour" min={25} max={100} disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} dedicated share`} value={r.secondaryShare} onChange={v => setResource(key, 'secondaryShare', v)} unit="%" max={100} disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} dedicated open`} value={r.secondaryOpen} onChange={v => setResource(key, 'secondaryOpen', v)} unit="units" step="1" disabled={locked} /><NumberField label={`${RESOURCE_META[key].short} PAX/transaction`} value={r.groupSize} onChange={v => setResource(key, 'groupSize', v)} unit="PAX" min={0.000001} disabled={locked || key === 'security'} /></div></div>; })}</div><p className="explain">A dedicated share creates a separate queue and its own unit count. The remaining open units form the primary pool. Security group size stays one passenger.</p></div>
        <div className="advanced-group"><h3>Assumption provenance</h3><p>Mark a group measured only when all inputs in it come from observed or calibrated data.</p><div className="provenance-list">{PROVENANCE_GROUPS.map(([key, label]) => <label key={key}>{label}<select value={scenario.provenance?.[key] || 'illustrative'} disabled={locked} onChange={e => setProvenance(key, e.target.value)}><option value="illustrative">Illustrative</option><option value="user-supplied">User-supplied</option><option value="measured">Measured / calibrated</option></select></label>)}</div><div className="provenance"><label>Source or calibration note<input type="text" value={scenario.sourceNote || ''} disabled={locked} onChange={e => setField('sourceNote', e.target.value)} placeholder="Optional date and source" /></label></div></div>
      </div>}</section>
      {whatif && <section className="panel comparison"><div className="panel-heading"><div><h2>Baseline vs what-if</h2><p>Same calculation direction; each scenario keeps its own inputs.</p></div><span className="compare-indicator">Scenario comparison</span></div>{baselineResult?.valid && whatifResult?.valid ? <div className="compare-grid"><div className="compare-row compare-head"><span>Measure</span><span>Baseline</span><span>What-if</span><span>Change</span></div><div className="compare-row"><strong>Originating PAX / h</strong><span>{fmt1(baselineResult.originating)}</span><span>{fmt1(whatifResult.originating)}</span><span>{fmt1(whatifResult.originating - baselineResult.originating)}</span></div>{RESOURCE_KEYS.map(key => { const a = baselineResult.resources[key], b = whatifResult.resources[key]; const av = mode === 'demand' ? a.recommended : a.capacity, bv = mode === 'demand' ? b.recommended : b.capacity; return <div className="compare-row" key={key}><strong>{RESOURCE_META[key].label}{mode === 'capacity' && <small>originating PAX / h</small>}</strong><span>{fmt1(av)}</span><span className={mode === 'demand' ? 'blue-text' : 'teal-text'}>{fmt1(bv)}</span><span>{Number.isFinite(av) && Number.isFinite(bv) ? `${bv - av > 0 ? '+' : ''}${fmt1(bv - av)}` : '—'}</span></div>; })}<div className="compare-row"><strong>{mode === 'capacity' ? 'Modelled system capacity' : 'Total open units'}</strong><span>{mode === 'capacity' ? fmt1(baselineResult.systemCapacity) : fmt(RESOURCE_KEYS.reduce((sum, key) => sum + baselineResult.resources[key].recommended, 0))}</span><span>{mode === 'capacity' ? fmt1(whatifResult.systemCapacity) : fmt(RESOURCE_KEYS.reduce((sum, key) => sum + whatifResult.resources[key].recommended, 0))}</span><span>—</span></div></div> : <p className="comparison-error">Correct both scenarios' inputs to compare results.</p>}</section>}
      <div className="reference-panel"><div><span className="kicker">Planning reference</span><h2>Replace illustrative assumptions with observed airport data.</h2><p>Peak arrivals, route shares, service times, open positions and queue structure determine the answer. Save the scenario with its source note for review.</p></div><div className="reference-item"><span>Input basis</span><strong>{scenario.demandBasis === 'direct' ? 'Peak arrivals' : scenario.demandBasis === 'departing-hour' ? 'Departing hour' : 'Annual bridge'}</strong><small>{provenanceSummary(scenario)}</small></div><div className="reference-item"><span>Queue target</span><strong>{fmt(scenario.resources.counter.targetPercent)}% / {fmt1(scenario.resources.counter.targetMinutes)} min</strong><small>Counter setting shown; each process is editable</small></div></div>
      <Methodology />
    </main><footer><span>Passenger Processing & Resource Calculator · Process-planning estimate</span><span>Illustrative until calibrated · Model version 1.0</span></footer>
  </div>;
}
